### ISSUE TITLE
cloverHDA Mojave 10.14 ALC256

### ISSUE THREAD

**Issue by sp2003** [insanelydeepak/cloverHDA-for-Mac-OS-Mojave-10.14#2]
Hi

can i use kext for High Sierra on Mojave ?
sound is ALC256 on a Notebook

**Comment by rajverma1985** [comment]
give it a shot it might work as well, but make sure you put that in /s/l/e

**Comment by insanelydeepak** [comment]
Hi 
is still you have issue ?? i was out of hometown from 15 days , im back 

let me know if still you need help

**Comment by sp2003** [comment]
hi

I try to solve the problem for 15 days, without success.
I installed the kext in S / L / E, applied the patch to the config.plist, changed the layout-id 5,11,13,28,56 but I got the audio only from the earphones with id 28 and 56.
Now I was trying VoodooHDA even without success.
I dont know what to do

**Comment by insanelydeepak** [comment]
send me codec dump

**Comment by sp2003** [comment]
[codec_dump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Mojave-10.14/files/2962949/codec_dump.txt)

by 
cat /proc/asound/card0/codec#0 > ~/Desktop/codec_dump.txt

**Comment by sp2003** [comment]
[debug_20909.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Mojave-10.14/files/2963255/debug_20909.zip)

if it can help

**Comment by insanelydeepak** [comment]
use this config files and remove voodoo + cloverHDA Files
[FILES.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Mojave-10.14/files/2964365/FILES.zip)

**Comment by sp2003** [comment]
after reboot audio is disabled. But must inject some layout-id in config.plist?
actually is empty

**Comment by sp2003** [comment]
UPDATE

i tried 5,7,11,13,28,56 layout-id whit same result, no device detect

**Comment by insanelydeepak** [comment]
why you injecting layout id ?? leave it 

just use my files and send me debug files

**Comment by sp2003** [comment]
i tried with and without...
[debug_4063.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Mojave-10.14/files/2966162/debug_4063.zip)

**Comment by insanelydeepak** [comment]
try this kext 
[AppleALC.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Mojave-10.14/files/2966408/AppleALC.kext.zip)

**Comment by sp2003** [comment]
YEAH!!!

and finnaly my audio play!!!!

**Comment by insanelydeepak** [comment]
enjoy good sound
